### ISSUE TITLE
not working with docker-machine 0.3.0

### ISSUE THREAD

**Issue by foleymic** [adlogix/docker-machine-nfs#1]
I upgraded to docker-machine 0.3.0 today and the volume no longer mounted inside the VM.  Looks to be a timing issue - I added a sleep 10 to the start of the  bootlocal.sh script and it seems to be working fine now.

**Comment by tonivdv** [comment]
Hey @foleymic ,

Thank you for the feedback. I will check that out today. If you want you can always propose a PR.

Cheers

**Comment by tonivdv** [comment]
Hey @foleymic ,

I upgraded and tried it, but I got other issues. Seems the docker-machine restart causes randomly "exit status 1" errors.

Do you got those errors too?

In addition to that, it seems odd that adding the 'sleep 10' in the beginning of the bootlocal.sh, solves your timeout issue. 

Can you copy paste the exact bootlocal.sh file?

Thank you

**Comment by silvamerica** [comment]
I'm also experiencing this issue. Adding a sleep did not help.

**Comment by foleymic** [comment]
Here is my altered bootlocal.sh file:
sleep 10
    sudo umount /Users
    sudo /usr/local/etc/init.d/nfs-client start
    sudo mount -t nfs -o noacl,async 192.168.99.1:/Users /Users

Please understand that I am not suggesting that sleep 10 is necessarily the right solution, more of a workaround until we figure out the underlying timing issue.  What led me to think it was timing was that the first line to umount /Users seemed to work, but not the mount.

**Comment by tonivdv** [comment]
Hello,

It seems at least one other user has the issue of restarts too https://github.com/docker/machine/issues/1412

So I'm wondering if there is anything to fix here or if there isn't a bigger issue in machine 0.3.0 ...

**Comment by timbrandin** [comment]
Upgrading docker-machine to v0.3.1 solves this issue.

``` bash
curl -L https://github.com/docker/machine/releases/download/v0.3.1/docker-machine_darwin-amd64 > /usr/local/bin/docker-machine &&
sudo chmod +x /usr/local/bin/docker-machine 
```

**Comment by tonivdv** [comment]
Hello,

I confirm, v0.3.1 solved the issue.
