### ISSUE TITLE
Path conflicts with existing export

### ISSUE THREAD

**Issue by jmreicha** [adlogix/docker-machine-nfs#10]
Getting the following error when running:

```
exports:8: /Users conflicts with existing export /Users/josh/github
```

I am on an older version of VBox and docker-machine so will attempt upgrading.

**Comment by tonivdv** [comment]
Hey @jmreicha ,

Seems the same 'issue' as #6 ?!

**Comment by jmreicha** [comment]
Oops, yep that's the same issue.

**Comment by jmreicha** [comment]
If anybody comes across this, the fastest workaround I found was to edit `/etc/exports` and comment out the Vagrant entries, leaving only the docker-machine entry then rerunning `docker-machine-nfs`.

**Comment by williamboxhall** [comment]
Cheers @jmreicha ! Workaround worked for me

**Comment by phuang07** [comment]
Thanks @jmreicha it works!

**Comment by matt-halliday** [comment]
Hitting a problem going the other way. I use docker-machine but want to run a project just using plain old vagrant. The vagrant box won't up because of permissions issues when mounting the project into the box. `/User` in exports is blocking it. Any idea how to run these two in harmony?
