### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by mtibben** [adlogix/docker-machine-nfs#100]
It appears docker-machine-nfs is having problems running on macOS Catalina

```bash
+ docker-machine-nfs 99dev-v15 --mount-opts=noatime,nodiratime,vers=3,nolock,noacl,timeo=10 --force
[INFO] Configuration:

	- Machine Name: 99dev-v15
	- Shared Folder: /Users
	- Mount Options: noatime,nodiratime,vers=3,nolock,noacl,timeo=10
	- Force: true

[INFO] machine presence ... 			OK
[INFO] machine running ... 			OK
[INFO] Lookup mandatory properties ... OK

	- Machine IP: 192.168.99.102
	- Network ID: vboxnet0
	- NFSHost IP: 192.168.99.1

[INFO] Configure NFS ...

 !!! Sudo will be necessary for editing /etc/exports !!!
Password:
exports:3: exported dir/fs mismatch: /Users /System/Volumes/Data
```

It appears the error is occurring at
```
$ sudo nfsd checkexports
exports:3: exported dir/fs mismatch: /Users /System/Volumes/Data
$ echo $?
1
```

and likely caused by the APFS Volume Groups in Catalina making separate partitions appear as one logical filesystem

**Comment by tonivdv** [comment]
Hi @mtibben ,

I didn't upgrade yet so I cannot help figure this out at the moment. Maybe you can try and propose a PR?

**Comment by alessiopiazza** [comment]
@mtibben have you tried to set `--shared-folder=/System/Volumes/Data/Users` ?

**Comment by rivetmichael** [comment]
@alessiopiazza it does work when running `docker-machine-nfs` command, but then we you share a folder or file with a container it is empty

**Comment by PaulBrandt** [comment]
Im facing the same problem and setting the hosts path with /System/Volumes/Data/[...] seems to fix the problems at first (I even see all the files) but the guest is not able to write files as it was earlier. So there seems to be some follow-up problems.

**Comment by mtibben** [comment]
Here's the approach taken by Vagrant to the same problem https://github.com/hashicorp/vagrant/pull/11108

**Comment by tonivdv** [comment]
Thanks @mtibben for providing a fix.

Can everybody try it out and share feedback on the PR. As said, I didn't migrate yet so can't test it out (yet)

**Comment by PaulBrandt** [comment]
What I had to do:
- add /System/Volumes/Data to the nfs path as stated above
- add /System/Volumes/Data to all the volume paths I have in my docker-compose.yml

(Inspired by the Vagrant Issue - They edited their Vagrant-File)

I think this is the reason why @rivetmichael has empty folders in his guest. Do you maybe need to add the prefix in your docker-compose.yml as well?

Edit: (Done before the fix was provided - WIll test the fix with original configs)

**Comment by PaulBrandt** [comment]
#102 created my /etc/export including the /System/Volumes/Data prefix. 
After removing all the manually set prefixes in my docker-compose.yml everything worked.
👍  for the fix

**Comment by rivetmichael** [comment]
@PaulBrandt thanks, I am trying this right now 👍

**Comment by rivetmichael** [comment]
thanks @mtibben and @PaulBrandt works fine with your PR

**Comment by nathpaiva** [comment]
Hello guys, I updated my `macOs` and I'm trying to execute the command `docker-machine-nfs default --shared-folder=/System/Volumes/Data/Users --force`, but I have some errors.

```bahs
± docker-machine-nfs default --shared-folder=/System/Volumes/Data/Users
[INFO] Configuration:

	- Machine Name: default
	- Shared Folder: /System/Volumes/Data/Users
	- Mount Options: noacl,async,nfsvers=3
	- Force: false

[INFO] machine presence ... 			OK
[INFO] machine running ... 			OK
[INFO] Lookup mandatory properties ... OK

	- Machine IP: 192.168.99.106
	- Network ID: vboxnet0
	- NFSHost IP: 192.168.99.1

[INFO] Configure NFS ...

 !!! Sudo will be necessary for editing /etc/exports !!!
Password:
Unknown user:
map credential error
exports:3: error processing options: -mapall=:501:20
exports:9: /System/Volumes/Data/Users conflicts with existing export /System/Volumes/Data/Users/nathpaiva/www
```

Someone knows, how can I fix this?

**Comment by nathpaiva** [comment]
Even if I pass the folder I want to share, like:
`docker-machine-nfs default --shared-folder=/System/Volumes/Data/Users/nathpaiva/www --force`

I receive this error.
```bash
Unknown user:
map credential error
exports:3: error processing options: -mapall=:501:20
```

**Comment by tonivdv** [comment]
Hey @nathpaiva ,

As the error tells you, you have a conflicting configuration in your /etc/exports file.

Remove the line with `/System/Volumes/Data/Users/nathpaiva/www` and try again.

Cheers

**Comment by nathpaiva** [comment]
Yeah, of course! I didn't think to check this. 🤦‍♀️

I remove from there and everything works fine. Thanks @tonivdv

**Comment by frankgraave** [comment]
I have the same kind of error:
exports:3: /System/Volumes/Data/Users conflicts with existing export /System/Volumes/Data

I'm running "docker-machine-nfs default"

But how to 'remove the line' as @tonivdv says?

Thanks in advance!

**Comment by nathpaiva** [comment]
@frankgraave go to `/etc/exports` and delete all data about the path you are passing.

And do the upgrade version with `brew upgrade docker-machine-nfs` and try again `docker-machine-nfs default`.

This is worked to me.

**Comment by frankgraave** [comment]
Ah, I see now 🤦‍♂ Sorry, long day and I wasn't reading quite well 😅 Thanks for pointing it out @nathpaiva!
