### ISSUE TITLE
:+1:

### ISSUE THREAD

**Issue by tut-tuuut** [adlogix/docker-machine-nfs#15]
Hello!

Just wanted to say thank you.
It just works, it's easy to use, and it GREATLY improves performance. :heart: :heart: :heart: :heart: 

Just had the same issue as #12 : NFS volume was not mounted due to host network latency. A reboot of my macbook has fixed it.

**Comment by tonivdv** [comment]
Hello @tut-tuuut ,

Glad it was useful and thanks for the kind words. 

Cheers
