### ISSUE TITLE
Customize which directory is mounted

### ISSUE THREAD

**Issue by adrienbrault** [adlogix/docker-machine-nfs#16]
Allow to specify one or more directories to mount.

Having vagrant shares in /etc/exports, the /Users one conflicts

**Comment by frankcarey** [comment]
This issue would also be required to make this work. https://github.com/docker/machine/pull/2100

**Comment by tonivdv** [comment]
Hey,

I worked a bit on that, and you can already play with my branch [feature/custom-share](https://github.com/adlogix/docker-machine-nfs/tree/feature/custom-share)

It only allows to substitute the /Users with another folder, but soon it will be possible to do multiple ones as @adrienbrault wrote.

You can test it by executing:

``` bash
./docker-machine-nfs.sh box -s=/opt/docker
```

Let me know your first thoughts on this.

Cheers
