### ISSUE TITLE
Customize the NFS -mapall param in /etc/exports

### ISSUE THREAD

**Issue by tonivdv** [adlogix/docker-machine-nfs#17]
Currently the /etc/exports file gets configured with:

```
-mapall=$(id -u):$(id -g)
```

However it seems for some (#14) this causes permissions issues and needs to be replace with some other values or be substituted with `-maproot=0`

The idea would be to allow to send the /etc/exports params through the docker-machine-nfs command:

E.g.

```
./docker-machine-nfs [machine] --nfs-exports="-maproot=0"
```

**Comment by arosenhagen** [comment]
:+1:

**Comment by ckortekaas** [comment]
+1
