### ISSUE TITLE
VMware Fusion support?

### ISSUE THREAD

**Issue by adambiggs** [adlogix/docker-machine-nfs#21]
Just found this script and it seems to work great for VirtualBox. But I was just wondering how hard it would be to add VMware Fusion support.

**Comment by tonivdv** [comment]
Hello @adambiggs ,

Good question :) I don't use that, but if anyone uses it and can help on that, I'll gladly merge it.

**Comment by ckortekaas** [comment]
What i've added in the above PR works for me.. but very happy to get feedback. Full details are in the PR comment.
