### ISSUE TITLE
Error on restarting machine

### ISSUE THREAD

**Issue by jgsqware** [adlogix/docker-machine-nfs#28]
Hi,

I got an error like that

```
[INFO] Restart Docker Machine ...       /usr/local/bin/VBoxManage showvminfo fast-io --machinereadable failed:
VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), callee nsISupports
VBoxManage: error: Context: "COMGETTER(RemoteUSBDevices)(ComSafeArrayAsOutParam(coll))" at line 2022 of file VBoxManageInfo.cpp
```

at the end of the script.

I can restart the machine after that with `docker-machine start mymachine`.

I put it here for instance ;)

**Comment by tonivdv** [comment]
Not sure it's related to the script, but more to https://github.com/docker/machine/issues/2494

**Comment by tonivdv** [comment]
I'm gonna close this issue, as it's not related to the nfs scripting. Should it be, or if you have other info don't hesitate to reopen.

Cheers
