### ISSUE TITLE
Example with docker-compose

### ISSUE THREAD

**Issue by thalesfsp** [adlogix/docker-machine-nfs#30]
Hello ;)

 I have been trying to get PM2/nodemon NodeJS hot-reload working. I tried I lot of different approaches and arrived here. I looked for an example and could not find. How can use it?

Cheers!

**Comment by tonivdv** [comment]
Hello @thalesfsp ,

Do you have issue specifically due to the nfs setup? If not you should ask those questions on another platform like stackoverflow.

Cheers
