### ISSUE TITLE
[Question] Is there anything like this for Windows?

### ISSUE THREAD

**Issue by artemgordinskiy** [adlogix/docker-machine-nfs#42]
Does anyone know if it's possible to use NFS/SMB shares on Windows to improve performance?
Asking for a friend (a colleague, actually).

P.S. Sorry for abusing your issues.

**Comment by tonivdv** [comment]
Hey @ArtemGordinsky ,

No worries. Last time I checked NFS on windows was not that easy and out of the box :( 

One dev I know who has a windows machine simply runs a real linux (read not boot2docker) and uses that box as dev environment. He even runs the IDE in there etc. But it requires the necessary amount of mem and disk space. But at least he can use natively docker.

Hope you can do something with that.

Cheers

**Comment by artemgordinskiy** [comment]
Thanks!
I guess either Docker is not popular enough on Windows, or it doesn't bother Windows users enough to do something about its dreadful performance there.

**Comment by tonivdv** [comment]
You could find the answer maybe on the vagrant community. Because in the end it's not really related to docker, but more with virtualbox or other vm tool.

**Comment by artemgordinskiy** [comment]
Thanks for the tips! Looks like Vagrant has a nice NFS plugin we can use. Will look into replacing Docker Machine with Vagrant.

**Comment by tonivdv** [comment]
Not sure it will work out of the box either :(

> Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.

**Comment by artemgordinskiy** [comment]
Yeah, turns out it's kind of a pain.
In the end we simply recreated the Docker Machine with the [VMWare Workstation driver](https://github.com/pecigonzalo/docker-machine-vmwareworkstation) which gave us performance, subjectively comparable to NFS on OS X. Seems to work pretty well for now :)
