### ISSUE TITLE
Setup fails on docker 1.10.0 and virtual box 5.0.14

### ISSUE THREAD

**Issue by skiss9** [adlogix/docker-machine-nfs#46]
I am using docker 1.10.0, virtual box 5.0.14 on OS X 10.10.5.

The NFS shared volumes worked fine for me until I updated docker toolbox from 1.9.0 to 1.10.0 so issue seems related to this update.

After running the script, the /etc/exports on the host has the expected entry, but the df command doesn't list the NFS entry that it used to list. As a result the script errors out with "Cannot detect the NFS mount :(" during the "Verify NFS mount" step.

**Comment by skiss9** [comment]
Never mind, updating to the latest version of docker-machine-nfs fixed it. Looks like you've already shipped a fix. Thanks for being so reactive!

**Comment by tonivdv** [comment]
Hey @stkiss ,

We did not really do things specifically for 1.10 but there have been some enhancements regarding nfs detection. Probably you still had a much older version.

Anyway I'm glad it works :)

Cheers
