### ISSUE TITLE
Shebang says sh, but gives a syntax error

### ISSUE THREAD

**Issue by frankcarey** [adlogix/docker-machine-nfs#49]
I'm testing this on ubuntu 14.04 (I know.. not OSX.. but I'm trying to setup machine to standardize setups across linux and OSX), but running the command gives an syntax error of : 

```
130: /usr/local/bin/docker-machine-nfs: Syntax error: "(" unexpected (expecting "}")
```

.. which is related to the creation of an empty bash array.

Is there a reason to not use /bin/bash instead, which resolves this specific issue?

**Comment by tylers-username** [comment]
This does depend on bash. I get this error when using zsh.

**Comment by tonivdv** [comment]
Hey @frankcarey ,

It works with bash. Check https://github.com/adlogix/docker-machine-nfs/issues/75 

Cheers
