### ISSUE TITLE
Add option to set IP or IP range

### ISSUE THREAD

**Issue by frankcarey** [adlogix/docker-machine-nfs#53]
There's another issue mentioning the problem when a restart changes the IP address of the machine causing the nfs share to break.  Since all the IPs are in a set range, it would be nice to have the option to use the range instead.

For instance this works for me, no matter what ip the machine starts on: 

```
#/etc/export
/home/fcarey/docker-share 192.168.99.0/24(rw,sync,no_subtree_check,no_root_squash)
```

Note these are linux specific settings but the important part is `192.168.99.0/24`

**Comment by vultron81** [comment]
We could really use this option.  Our problem is that docker-machine-nfs uses the public IP of the machine.  If you change networks (like you have a laptop and bring it home) the public IP changes and you have to rerun the docker-machine-nfs script.  It would be better to have the VM route IP by default as this does not change when you change networks.

**Comment by seanmrogers** [comment]
+1

**Comment by johnlouie** [comment]
+1

**Comment by mjaffasofi** [comment]
+1

**Comment by Gabrinthei** [comment]
+1 would be a great addition

**Comment by fuerst** [comment]
Is the host IP needed at all? I usually use the IP range of the VM network adapter the boot2docker VM runs at like:

```
/Users -alldirs -mapall=502:20 -network 172.16.12.0 -mask 255.255.255.0
```

Since the network adapter usually does not change between restarts or change of network location this would be a better solution in my point of view.

**Comment by tonivdv** [comment]
Hey guys,

I added a way to have the ip-range. If you want to test the PR it's now the time to do it ;)

Cheers
