### ISSUE TITLE
Virtualbox host only /24

### ISSUE THREAD

**Issue by rmb938** [adlogix/docker-machine-nfs#62]
It would be nice if the exported mount is configured for the whole /24 ip space for the host only network. The VM ip changes sometimes so it would be nice to not have to rerun the script when that happens.

**Comment by tonivdv** [comment]
Hey @rmb938 ,

Thanks for the feedback. Could it be that the request is the same as #53 ?

fwiw we use this workaround to avoid ip changes on restart of the machine: https://github.com/docker/machine/issues/1709#issuecomment-161026484

> 192.168.98.100
> docker-machine create -d virtualbox --virtualbox-hostonly-cidr "192.168.98.1/24" m98
> 
> 192.168.97.100
> docker-machine create -d virtualbox --virtualbox-hostonly-cidr "192.168.97.1/24" m97
> 
> 192.168.96.100
> docker-machine create -d virtualbox --virtualbox-hostonly-cidr "192.168.96.1/24" m96

Hope this helps

**Comment by rmb938** [comment]
Ah yes, sorry for the duplicate.
