### ISSUE TITLE
mounting {ip}:/Users on /Users failed: Bad file descriptor

### ISSUE THREAD

**Issue by bennypowers** [adlogix/docker-machine-nfs#64]
docker-machine 0.8.1
el cap

``` fish
begin
  curl -s https://raw.githubusercontent.com/adlogix/docker-machine-nfs/master/docker-machine-nfs.sh |  sudo tee /usr/local/bin/docker-machine-nfs > /dev/null
  sudo chmod +x /usr/local/bin/docker-machine-nfs
  docker-machine rm dev
  docker-machine create -d virtualbox dev
  docker-machine-nfs dev --nfs-config="-alldirs -maproot=0"
end 
```

👇👇👇

```
Cannot detect the NFS mount :(
```

🙁🙁🙁

```
docker-machine ssh dev sudo mount -t nfs -o noacl,async 192.168.99.1:/Users /Users
mount: 192.168.99.1:/Users failed, reason given by server: Permission denied
mount: mounting 192.168.99.1:/Users on /Users failed: Bad file descriptor
```

**Comment by ellisio** [comment]
This is happening for me as well.
- macOS Sierra
- Docker Machine 0.8.2
- Docker 1.12.2
- VirtualBox 5.1.8 r111374

Installed via the Homebrew method. Ran `docker-machine-nfs default`, nothing fancy.

**Comment by ellisio** [comment]
PR #65 submitted for this issue. In the mean time, edit line 357 and remove the `-network` flag. This will fix `/etc/exports` and initialize NFS correctly on macOS.

**Comment by ahansson89** [comment]
Worked for me on 

macOS Sierra
Docker Machine 0.8.2
Docker 1.12.2
VirtualBox 5.1.8 r111374

**Comment by tonivdv** [comment]
That's interesting. I don't have any issues on my setup ...

macOs Sierra
Docker Machine 0.8.2
Docker 1.12.2
VirtualBox 5.1.6 r110634

What do you get when running `nfsd checkexports` ?

**Comment by tonivdv** [comment]
On second thought, I do have the issue now ... But it does work for the ip-range. So the -network flag should only be used when the ip-range config is being used

**Comment by bennypowers** [comment]
confirmed fix thanks
