### ISSUE TITLE
So frustrated with docker for mac

### ISSUE THREAD

**Issue by raptor235** [adlogix/docker-machine-nfs#70]
Hey guys,

This is not really a bug but just trying to gain some understand of what's going on... I've been running docker-machine-nfs for a while now... tried to switch to docker for mac a few times but I just can't stomach the slow speed.... how can they push that product so hard when it's so bad at performance... doesn't anyone else have the same issues?

For example I'm running the same site, same db, same codebase... on a new mbp 2016 that I just installed and this is the results of a WordPress backend...

Docker for mac (16s load time)
http://i.imgur.com/EyV50vO.png

Docker toolbox (6s load time)
http://i.imgur.com/fKGmhgD.png

Docker toolbox NSF mounted (https://github.com/adlogix/docker-machine-nfs) (2s load time)
http://i.imgur.com/lk0LhNL.png

Horrible... anyone else experiencing the same thing?

Saying that is docker-machine-nfs something that will be made available for docker for mac? I'm really hoping they don't EOL docker toolbox anytime soon.

Thanks

**Comment by tonivdv** [comment]
Hey @raptor235 ,

I completely understand the feeling. It was my first reaction when I test d4m during their private beta testing phase. 

However if you wish to have nfs you could use https://github.com/IFSight/d4m-nfs . I didn't test this personally (yet), but it should be working as someone (https://github.com/adlogix/docker-machine-nfs/issues/68) asked if it was possible to add it in this project too.

I think the idea is to move all to something like D4M, but they need to at least have nfs support or any other technique.
