### ISSUE TITLE
VMWare Fusion problems on macOS 10.12

### ISSUE THREAD

**Issue by Starefossen** [adlogix/docker-machine-nfs#73]
I had difficulties solving some shared directories problems with Docker on VMWare Fusion on macOS 10.12. What solved my problem was disabling shared folders for the Docker Machine form inside the VMWare Fusion control panel before running `docker-machine-nfs`.

<img width="752" alt="screen shot 2017-01-24 at 23 17 30" src="https://cloud.githubusercontent.com/assets/968267/22269346/4c4bede2-e28b-11e6-9f92-81c488a526b5.png">

Also, remember to disable any active VPN connections while running `docker-machine-nfs` or else it will end up with the wrong IP address for the network share.

---

*Feel free to close this, or if you like, I can PR the README with these instructions.*

**Comment by tonivdv** [comment]
Hey @Starefossen ,

Thanks for sharing. I currently don't have Fusion on my machine so can't quickly verify if I have the same issue. However it can certainly be useful for others to have this in the readme as a kind of FAQ or Known Issues section

Cheers
