### ISSUE TITLE
Not working with Parallels 12 Pro on Sierra

### ISSUE THREAD

**Issue by mchadwickchennault** [adlogix/docker-machine-nfs#74]
OS version: 10.12.3
Parallels version: 12.1.3

Attempting to share the user directory fails at the `Verify NFS mount` message.

**Comment by tonivdv** [comment]
@mchadwickchennault would you be able to provide the fix? We are not using Parallels so it could take some time to have a fix.

**Comment by mchadwickchennault** [comment]
Turns out this is not an issue. The problem was an anit-virus program installed by my IT department. Closing issue. Sorry for the fire drill.

**Comment by tonivdv** [comment]
@mchadwickchennault No problem. Is good to know this can cause issues too ;)
