### ISSUE TITLE
Stale file handle

### ISSUE THREAD

**Issue by fdellutri** [adlogix/docker-machine-nfs#77]
Hi,
In docker-compose.yml  I have mounted a single file, as follows:
```
volumes:
      - app/config:/var/www/app/config
      - composer.json:/var/www/composer.json
```

When I edit the composer.json from an external editor (Idea), the container is unable to access the file anymore, and it raises the following error:
```
# cat composer.json 
cat: composer.json: Stale file handle
```

**Comment by tonivdv** [comment]
Hi @fdellutri ,

Are you using latest releases?

**Comment by fdellutri** [comment]
Client:
 Version:      17.04.0-ce
 API version:  1.24 (downgraded from 1.28)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 23:33:17 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24 (minimum version )
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
 Experimental: false

docker-machine version 0.10.0, build 76ed2a6

**Comment by tonivdv** [comment]
@fdellutri Already tried to upgrade docker version on the server?

**Comment by tonivdv** [comment]
@fdellutri  were you able to solve the issue?
