### ISSUE TITLE
The script mentions boot2docker.

### ISSUE THREAD

**Issue by squaresurf** [adlogix/docker-machine-nfs#8]
It is confusing to read the function declarations that mention boot2docker, but as far as I can tell `boot2docker` is not used. Since `docker-machine` is the future, it would be best to refactor so that boot2docker is not mentioned.

**Comment by silvamerica** [comment]
Docker Machine still uses the boot2docker.iso under-the-hood for creating a Virtual machine locally, so many of the comments still make sense in that context.

**Comment by squaresurf** [comment]
Some of the function names do not make sense though:
- https://github.com/adlogix/docker-machine-nfs/blob/master/docker-machine-nfs.sh#L150
- https://github.com/adlogix/docker-machine-nfs/blob/master/docker-machine-nfs.sh#L150

:point_up: do not start or configure `boot2docker`.

**Comment by squaresurf** [comment]
I can open a PR in a bit if no one is opposed to it. I wanted to get some input first though to make sure I was understanding it all correctly.

**Comment by silvamerica** [comment]
For sure. I agree that the comments (especially the user-facing ones) can be updated, but I just wanted to make sure that you and other readers of this issue understand that boot2docker is still used even though it is through docker-machine.

**Comment by squaresurf** [comment]
Awesome, I didn't realize that. Does it make sense to you to update any references to boot2docker with docker-machine unless it is in reference to the iso?

**Comment by silvamerica** [comment]
That sounds reasonable to me. If you'd like, I can review the PR if you cc
me.
