### ISSUE TITLE
grep is not working

### ISSUE THREAD

**Issue by beardcoder** [adlogix/docker-machine-nfs#88]
Use indeed 
if [ "$(cat /etc/nfs.conf | grep -c "$nfsd_line")" == "1" ]; then

This local the string "nfs.server.mount.require_resv_port = 0" corecctly

**Comment by tonivdv** [comment]
Hi @beardcoder ,

Can you elaborate a bit more. 

Thank you

**Comment by beardcoder** [comment]
Hello,
no problem.

On macOS the check if the line "nfs.server.mount.require_resv_port = 0"  doesn't work. On each run the file nfs.conf will be overwritten.

The solution is to change to cat and pip the result to grep.

**Comment by tonivdv** [comment]
This is only for the vmware fusion driver right? Can you provide a PR?

**Comment by beardcoder** [comment]
yes i can ^^
